export const apiEndpoints = {
  adminPlans: {
    list: () => "/admin/plans",
    get: (planId: string) => `/admin/plans/${planId}`,
    create: () => "/admin/plans",
    update: (planId: string) => `/admin/plans/${planId}`,
    delete: (planId: string) => `/admin/plans/${planId}`,
    features: (planId: string) => `/admin/plans/${planId}/features`,
    limits: (planId: string) => `/admin/plans/${planId}/limits`,
    duplicate: (planId: string) => `/admin/plans/${planId}/duplicate`,
    reorder: () => "/admin/plans/reorder",
  },
  adminDatabasePlans: {
    list: () => "/admin/database-plans",
    get: (planId: string) => `/admin/database-plans/${planId}`,
    create: () => "/admin/database-plans",
    update: (planId: string) => `/admin/database-plans/${planId}`,
    delete: (planId: string) => `/admin/database-plans/${planId}`,
    duplicate: (planId: string) => `/admin/database-plans/${planId}/duplicate`,
  },
  adminEmailPlans: {
    list: () => "/admin/email-plans",
    get: (planId: string) => `/admin/email-plans/${planId}`,
    create: () => "/admin/email-plans",
    update: (planId: string) => `/admin/email-plans/${planId}`,
    delete: (planId: string) => `/admin/email-plans/${planId}`,
    duplicate: (planId: string) => `/admin/email-plans/${planId}/duplicate`,
  },
  adminSupport: {
    tickets: () => "/admin/support/tickets",
    ticket: (ticketId: string) => `/admin/support/tickets/${ticketId}`,
    messages: (ticketId: string) => `/admin/support/tickets/${ticketId}/messages`,
    attachmentDownload: (ticketId: string, attachmentId: string) =>
      `/admin/support/tickets/${ticketId}/attachments/${attachmentId}/download`,
  },
  adminResources: {
    overview: () => "/admin/resources",
    traffic: () => "/admin/resources/traffic",
    block: (resourceId: string) => `/admin/resources/${resourceId}/block`,
    unblock: (resourceId: string) => `/admin/resources/${resourceId}/unblock`,
    transfer: (resourceId: string) => `/admin/resources/${resourceId}/transfer`,
    coolifyOrphans: () => "/admin/resources/coolify-orphans",
    claimCoolifyOrphan: () => "/admin/resources/coolify-orphans/claim",
  },
  adminUsers: {
    search: () => "/admin/users",
    projects: (userId: string) => `/admin/users/${userId}/projects`,
  },
  adminCustomers: {
    list: () => "/admin/customers",
    resources: (userId: string) => `/admin/customers/${userId}/resources`,
  },
  adminPayments: {
    overview: () => "/admin/payments",
  },
  adminInvoices: {
    list: () => "/admin/invoices",
    customers: () => "/admin/invoices/customers",
    preview: () => "/admin/invoices/preview",
    create: () => "/admin/invoices",
    get: (invoiceId: string) => `/admin/invoices/${invoiceId}`,
    update: (invoiceId: string) => `/admin/invoices/${invoiceId}`,
    sendReceipt: (invoiceId: string) => `/admin/invoices/${invoiceId}/send-receipt`,
  },
  adminCoupons: {
    list: () => "/admin/coupons",
    get: (couponId: string) => `/admin/coupons/${couponId}`,
    create: () => "/admin/coupons",
    update: (couponId: string) => `/admin/coupons/${couponId}`,
    delete: (couponId: string) => `/admin/coupons/${couponId}`,
  },
  adminDockerfileAudit: {
    get: () => "/admin/dockerfile-audit",
    update: () => "/admin/dockerfile-audit",
  },
} as const;
